coverage:
  status:
    project:
      default:
        # basic
        target: 80%
        threshold: 1%
ignore:
  - "/Users/rgederin/github/spring-boot-rest-api-cicd/src/main/java/com/gederin/api/model"